#!/bin/bash

rm -fr konqueror

tar xfz konqueror.tar.gz

cd konqueror

source /witech/arm-qtopia/qtopia2.2.0path/qtopia2.2.0/setQpeEnv

CC=arm-linux-gcc CXX=arm-linux-g++  LDFLAGS=-ldl CROSS_COMPILE=1 ./configure --enable-embedded --enable-qt-embedded --enable-qpe --disable-debug --enable-static --disable-shared --disable-mt --without-ssl --with-qt-dir=$QTDIR --with-qt-includes=$QTDIR/include --with-qt-libraries=$QPEDIR/lib --with-qtopia-dir=$QPEDIR --with-gui=qpe --host=arm-linux --target=arm-linux

make
arm-linux-strip --strip-all konq-embed/src/konqueror
